language: cpp

before_install:
  - sudo pip install cpp-coveralls --use-mirrors
  - sudo apt-get update -qq
  - sudo apt-get install -y libasound2-dev libncurses5-dev libpulse-dev

script: 
  - ./run_testsuite.sh

after_success: #coveralls --exclude speech_tools/rxp --exclude speech_tools/testsuite --exclude speech_tools/java --exclude festival

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   # via the "travis encrypt" command using the project repo's public key
   - secure: "ABQ7dCZdtvuy6/TUlXWbUVJJktAFBl2BGigm50Kq3/kmWVUAzckc7IiNtd4yyvkWXcSMPSOaD5s2S5h15braGEoeSYJxoSArEoeMTA2YX8X8VxgsJgIIRtq2Ip9AVO5/5DvxkDNt8XBGRDiCTMQovRA2X5FU2+45YPjNIP0Soqg="

addons:
  coverity_scan:
    project:
      name: "zeehio/festival_suite"
      description: "Your project description here"
    notification_email: sergioller@gmail.com
    build_command_prepend: sudo apt-get update -qq && sudo apt-get install -y libasound2-dev libncurses5-dev libpulse-dev && ./configure #--enable-profile=gcov --with-pulseaudio
    build_command: make
    branch_pattern: coverity_scan

branches:
  only:
    - master
    - coverity_scan

