language: cpp

before_install:
  - sudo pip install cpp-coveralls --use-mirrors
  - sudo apt-get update -qq
  - sudo apt-get install -y libasound2-dev libncurses5-dev libpulse-dev autoconf xsltproc doxygen graphviz doxygen-latex

script: 
  - ./run_testsuite.sh

after_success: coveralls --exclude speech_tools/rxp --exclude speech_tools/testsuite --exclude speech_tools/java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   # via the "travis encrypt" command using the project repo's public key
   - secure: "o4UnnOxBCTRCKdK6R+Ss4xRXJ6Zc8cpotlPl7msEOIREF2fUEGU3tXRePxPD/HEF6wZBafTzS7QJpIlZHBuGtnQB1Sd4EJxQhmM+S37AAd4td6EGnDAPnfbw3xLj3f1tBnXaO7A+KPHLPsKtauUnUbaJUvfinFVqVMRBsoKkOI8="

addons:
  coverity_scan:
    project:
      name: "zeehio/festival_suite"
      description: "Your project description here"
    notification_email: sergioller@gmail.com
    build_command_prepend: sudo apt-get update -qq && sudo apt-get install -y libasound2-dev libncurses5-dev libpulse-dev autoconf && cd "speech_tools" && autoconf && ./configure --enable-profile=gcov #--with-pulseaudio
    build_command: make && cd "../festival" && ./configure && make
    branch_pattern: coverity_scan

branches:
  only:
    - master
    - coverity_scan

